-- Estadio y ciudad de cada partido (change estadio-ciudad, specs
-- match-schedule, data-seeding, admin-panel). Generado por
-- scripts/generate-fixture-seed.py; NO editar a mano. Columnas nullable
-- (partidos por definir V2) + backfill de los 72 partidos sembrados,
-- keyed por id oficial FIFA. Naming es-MX aprobado (VENUES).

alter table public.matches
  add column if not exists stadium text,
  add column if not exists city text;

update public.matches m
  set stadium = v.stadium, city = v.city
  from (values
    (1, 'Estadio Azteca', 'Ciudad de México'),
    (2, 'Estadio Akron', 'Guadalajara'),
    (3, 'BMO Field', 'Toronto'),
    (4, 'SoFi Stadium', 'Los Ángeles'),
    (5, 'Gillette Stadium', 'Boston'),
    (6, 'BC Place', 'Vancouver'),
    (7, 'MetLife Stadium', 'Nueva York'),
    (8, 'Levi''s Stadium', 'San Francisco'),
    (9, 'Lincoln Financial Field', 'Filadelfia'),
    (10, 'NRG Stadium', 'Houston'),
    (11, 'AT&T Stadium', 'Dallas'),
    (12, 'Estadio BBVA', 'Monterrey'),
    (13, 'Hard Rock Stadium', 'Miami'),
    (14, 'Mercedes-Benz Stadium', 'Atlanta'),
    (15, 'SoFi Stadium', 'Los Ángeles'),
    (16, 'Lumen Field', 'Seattle'),
    (17, 'MetLife Stadium', 'Nueva York'),
    (18, 'Gillette Stadium', 'Boston'),
    (19, 'Arrowhead Stadium', 'Kansas City'),
    (20, 'Levi''s Stadium', 'San Francisco'),
    (21, 'BMO Field', 'Toronto'),
    (22, 'AT&T Stadium', 'Dallas'),
    (23, 'NRG Stadium', 'Houston'),
    (24, 'Estadio Azteca', 'Ciudad de México'),
    (25, 'Mercedes-Benz Stadium', 'Atlanta'),
    (26, 'SoFi Stadium', 'Los Ángeles'),
    (27, 'BC Place', 'Vancouver'),
    (28, 'Estadio Akron', 'Guadalajara'),
    (29, 'Lincoln Financial Field', 'Filadelfia'),
    (30, 'Gillette Stadium', 'Boston'),
    (31, 'Levi''s Stadium', 'San Francisco'),
    (32, 'Lumen Field', 'Seattle'),
    (33, 'BMO Field', 'Toronto'),
    (34, 'Arrowhead Stadium', 'Kansas City'),
    (35, 'NRG Stadium', 'Houston'),
    (36, 'Estadio BBVA', 'Monterrey'),
    (37, 'Hard Rock Stadium', 'Miami'),
    (38, 'Mercedes-Benz Stadium', 'Atlanta'),
    (39, 'SoFi Stadium', 'Los Ángeles'),
    (40, 'BC Place', 'Vancouver'),
    (41, 'MetLife Stadium', 'Nueva York'),
    (42, 'Lincoln Financial Field', 'Filadelfia'),
    (43, 'AT&T Stadium', 'Dallas'),
    (44, 'Levi''s Stadium', 'San Francisco'),
    (45, 'Gillette Stadium', 'Boston'),
    (46, 'BMO Field', 'Toronto'),
    (47, 'NRG Stadium', 'Houston'),
    (48, 'Estadio Akron', 'Guadalajara'),
    (49, 'Hard Rock Stadium', 'Miami'),
    (50, 'Mercedes-Benz Stadium', 'Atlanta'),
    (51, 'BC Place', 'Vancouver'),
    (52, 'Lumen Field', 'Seattle'),
    (53, 'Estadio Azteca', 'Ciudad de México'),
    (54, 'Estadio BBVA', 'Monterrey'),
    (55, 'Lincoln Financial Field', 'Filadelfia'),
    (56, 'MetLife Stadium', 'Nueva York'),
    (57, 'AT&T Stadium', 'Dallas'),
    (58, 'Arrowhead Stadium', 'Kansas City'),
    (59, 'SoFi Stadium', 'Los Ángeles'),
    (60, 'Levi''s Stadium', 'San Francisco'),
    (61, 'Gillette Stadium', 'Boston'),
    (62, 'BMO Field', 'Toronto'),
    (63, 'Lumen Field', 'Seattle'),
    (64, 'BC Place', 'Vancouver'),
    (65, 'NRG Stadium', 'Houston'),
    (66, 'Estadio Akron', 'Guadalajara'),
    (67, 'MetLife Stadium', 'Nueva York'),
    (68, 'Lincoln Financial Field', 'Filadelfia'),
    (69, 'Arrowhead Stadium', 'Kansas City'),
    (70, 'AT&T Stadium', 'Dallas'),
    (71, 'Hard Rock Stadium', 'Miami'),
    (72, 'Mercedes-Benz Stadium', 'Atlanta')
  ) as v(id, stadium, city)
  where m.id = v.id;
